### ISSUE TITLE
ValueError: loss method not supported: scale`

### ISSUE THREAD

**Issue by KoyoImai** [Orienfish/SCALE#1]
I followed the README and executed the following, but an error occurred.
`cd OnlineContrast/scripts`
`bash ./run-scale.sh scale cifar10 iid 1`
Error is as follows.
`Traceback (most recent call last):`
`  File "main_supcon.py", line 545, in <module>`
`    main()`
`  File "main_supcon.py", line 491, in main`
`    criterion, criterion_reg = get_loss(opt)`
`  File "/home/SCALE/OnlineContrast/losses/__init__.py", line 15, in get_loss`
`    raise ValueError('loss method not supported: {}'.format(opt.criterion))`
`ValueError: loss method not supported: scale`
It seems that the loss method of scale is not supported in __init__.py.
How do I run SCALE?

**Comment by Orienfish** [comment]
Thanks for pointing out! That should be a bug, and it should be fixed now.
Please let me know if there are further issues :)

**Comment by KoyoImai** [comment]
Thanks for the correction and for getting back to me.
